apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: index.docker.io/examor/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 51818
        readinessProbe:
          httpGet:
            path: /
            port: 51818
          initialDelaySeconds: 15
      volumes:
      - name: tls-secret-volume
        secret:
          secretName: tls-secret-name


