apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 443  
    targetPort: 51818
  tls:
  - hosts:
    - 192.168.49.2
    secretName: tls-secret-name

