apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  serviceName: "database"
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      hostname: database  
      containers:
      - name: database
        image: dwaipayansom/examor-database:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
  podManagementPolicy: OrderedReady  
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
