apiVersion: v1
kind: Pod
metadata:
  name: server-database-pod
  labels:
    app: server-database
spec:
  initContainers:
  - name: wait-for-database
    image: busybox:1.32.0
    command: ['sh', '-c', 'until nc -z database 3306; do echo "Waiting for database to be ready..."; sleep 15; done;']
  containers:
  - name: server
    image: dwaipayansom/examor-server:latest
    ports:
    - containerPort: 51717
    readinessProbe:
      tcpSocket:
        port: 51717
      initialDelaySeconds: 15
  - name: database
    image: dwaipayansom/examor-database:latest
    ports:
    - containerPort: 3306
