apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-database
  template:
    metadata:
      labels:
        app: server-database
    spec:
      containers:
      - name: server
        image: dwaipayansom/examor-server:latest
        ports:
        - containerPort: 51717
      - name: database
        image: dwaipayansom/examor-database:latest
        ports:
        - containerPort: 52020
