apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: examor/server:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 51717
        readinessProbe:
          tcpSocket:
            port: 51717
          initialDelaySeconds: 15
      volumes:
      - name: tls-secret-volume
        secret:
          secretName: tls-secret-name

